# Generated by Django 2.2.6 on 2019-10-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pagecontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='noname')),
                ('shortdesc', models.TextField(default='shortdesc')),
                ('desc1', models.TextField(default='desc1')),
                ('desc2', models.TextField(default='desc2')),
            ],
        ),
    ]
